version: 1.0.{build}
environment:
  NugetApiKey:
    secure: TODO_ADD
build_script:
- ps: ./build.ps1 -target Package
artifacts:
- path: ./output/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: TODO_ADD
  on:
    appveyor_repo_tag: true